name: kahootify
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^7.0.0
  shared_preferences: ^2.0.5
  equatable: ^2.0.0
  web_socket_channel: ^2.0.0
  http: ^0.13.2
  dartz: ^0.10.0-nullsafety.1
  numberpicker: ^2.1.1
  wifi_iot: ^0.3.1
  flutter_spinkit: ^5.0.0
  font_awesome_flutter: ^9.0.0
  fluttertoast: ^8.0.6
  kahootify_server:
    path: packages/server


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true