name: kahootify_server
description: Dart package which manages the kahootify server
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ping_discover_network: ^0.2.0+1
  wifi: ^0.1.5
  web_socket_channel: ^2.1.0
  tuple: ^2.0.0
  enum_to_string: ^2.0.1


